Update buttons.css
mohamedelshamy55/Portfolio-mobile-menu pull request #4
Opened 2021-11-10 20:57 UTC by mohamedelshamy55

2021-11-10 23:34 UTC, carlos-ssh requested changes
Hi @mohamedelshamy55 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._


![changesrequested](https://user-images.githubusercontent.com/22258274/141210579-925f722e-c41c-46ba-95f3-78f8c7a18431.gif)




## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-10 23:34 UTC, carlos-ssh commented on main.js
> +  inputs,
**Kindly work on this requested changes:**
- Add a function to validate the email input that can check your input text, if it's typed correctly in lowercase.

2021-11-10 23:34 UTC, carlos-ssh commented on main.js
# 💾 💾 💽 [OPTIONAL]   💽 💾 💾
**✔️ _Keep professionalism in your Repo's_** 

You can improve your repositories management:
- Create a assets directory and save all your content there.

![Screen Shot 2021-11-10 at 17 33 08](https://user-images.githubusercontent.com/22258274/141210438-fcc1991b-72f2-4ee6-a01a-11f2612c21f0.png)

2021-11-11 07:01 UTC, AshakaE approved these changes
### Hi @mohamedelshamy55  🙋‍♀️, 

# STATUS APPROVED ✔
Your project is complete!  There is nothing else to say other than... it's time to merge it 🔗 🚢 
Congratulations! 🎉 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers 🥂  and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-11 07:27 UTC, merged